// Seed data for Movie Role Mapping
// Links persons to movies with their roles
// Note: Replace movieRef and personRef with actual ObjectIds when inserting into DB

const movieRoleMappingSeedData = [
  // ========== OPPENHEIMER ==========
  {
    movieRef: "Oppenheimer",
    personRef: "Cillian Murphy",
    role: "actor",
    characterName: "J. Robert Oppenheimer",
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "Oppenheimer",
    personRef: "Emily Blunt",
    role: "actress",
    characterName: "Kitty Oppenheimer",
    order: 2,
    isCameo: false,
  },
  {
    movieRef: "Oppenheimer",
    personRef: "Robert Downey Jr.",
    role: "actor",
    characterName: "Lewis Strauss",
    order: 3,
    isCameo: false,
  },
  {
    movieRef: "Oppenheimer",
    personRef: "Matt Damon",
    role: "actor",
    characterName: "Leslie Groves",
    order: 4,
    isCameo: false,
  },
  {
    movieRef: "Oppenheimer",
    personRef: "Christopher Nolan",
    role: "director",
    characterName: null,
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "Oppenheimer",
    personRef: "Emma Thomas",
    role: "producer",
    characterName: null,
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "Oppenheimer",
    personRef: "Florence Pugh",
    role: "actress",
    characterName: "Jean Tatlock",
    order: 5,
    isCameo: false,
  },
  {
    movieRef: "Oppenheimer",
    personRef: "Rami Malek",
    role: "actor",
    characterName: "David Hill",
    order: 6,
    isCameo: false,
  },
  {
    movieRef: "Oppenheimer",
    personRef: "Kenneth Branagh",
    role: "actor",
    characterName: "Niels Bohr",
    order: 7,
    isCameo: false,
  },
  {
    movieRef: "Oppenheimer",
    personRef: "Josh Hartnett",
    role: "actor",
    characterName: "Ernest Lawrence",
    order: 8,
    isCameo: false,
  },
  {
    movieRef: "Oppenheimer",
    personRef: "Dane DeHaan",
    role: "actor",
    characterName: "Major General Kenneth Nichols",
    order: 9,
    isCameo: false,
  },
  {
    movieRef: "Oppenheimer",
    personRef: "Hoyte van Hoytema",
    role: "producer",
    characterName: null,
    order: 3,
    isCameo: false,
  },

  // ========== BARBIE ==========
  {
    movieRef: "Barbie",
    personRef: "Margot Robbie",
    role: "actress",
    characterName: "Barbie",
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "Barbie",
    personRef: "Ryan Gosling",
    role: "actor",
    characterName: "Ken",
    order: 2,
    isCameo: false,
  },
  {
    movieRef: "Barbie",
    personRef: "America Ferrera",
    role: "actress",
    characterName: "Gloria",
    order: 3,
    isCameo: false,
  },
  {
    movieRef: "Barbie",
    personRef: "Kate McKinnon",
    role: "actress",
    characterName: "Weird Barbie",
    order: 4,
    isCameo: false,
  },
  {
    movieRef: "Barbie",
    personRef: "Will Ferrell",
    role: "actor",
    characterName: "CEO of Mattel",
    order: 5,
    isCameo: false,
  },
  {
    movieRef: "Barbie",
    personRef: "Simu Liu",
    role: "actor",
    characterName: "Ken (Another Ken)",
    order: 6,
    isCameo: false,
  },
  {
    movieRef: "Barbie",
    personRef: "Issa Rae",
    role: "actress",
    characterName: "President Barbie",
    order: 7,
    isCameo: false,
  },
  {
    movieRef: "Barbie",
    personRef: "Rhea Perlman",
    role: "actress",
    characterName: "Ruth Handler",
    order: 8,
    isCameo: false,
  },
  {
    movieRef: "Barbie",
    personRef: "Greta Gerwig",
    role: "director",
    characterName: null,
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "Barbie",
    personRef: "Noah Baumbach",
    role: "producer",
    characterName: null,
    order: 2,
    isCameo: false,
  },
  {
    movieRef: "Barbie",
    personRef: "Rodrigo Prieto",
    role: "producer",
    characterName: null,
    order: 3,
    isCameo: false,
  },

  // ========== THE DARK KNIGHT ==========
  {
    movieRef: "The Dark Knight",
    personRef: "Christian Bale",
    role: "actor",
    characterName: "Bruce Wayne / Batman",
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "The Dark Knight",
    personRef: "Heath Ledger",
    role: "actor",
    characterName: "Joker",
    order: 2,
    isCameo: false,
  },
  {
    movieRef: "The Dark Knight",
    personRef: "Aaron Eckhart",
    role: "actor",
    characterName: "Harvey Dent / Two-Face",
    order: 3,
    isCameo: false,
  },
  {
    movieRef: "The Dark Knight",
    personRef: "Michael Caine",
    role: "actor",
    characterName: "Alfred Pennyworth",
    order: 4,
    isCameo: false,
  },
  {
    movieRef: "The Dark Knight",
    personRef: "Morgan Freeman",
    role: "actor",
    characterName: "Lucius Fox",
    order: 5,
    isCameo: false,
  },
  {
    movieRef: "The Dark Knight",
    personRef: "Gary Oldman",
    role: "actor",
    characterName: "James Gordon",
    order: 6,
    isCameo: false,
  },
  {
    movieRef: "The Dark Knight",
    personRef: "Maggie Gyllenhaal",
    role: "actress",
    characterName: "Rachel Dawes",
    order: 7,
    isCameo: false,
  },
  {
    movieRef: "The Dark Knight",
    personRef: "Nestor Carbonell",
    role: "actor",
    characterName: "Mayor Anthony Garcia",
    order: 8,
    isCameo: false,
  },
  {
    movieRef: "The Dark Knight",
    personRef: "Eric Roberts",
    role: "actor",
    characterName: "Salvatore Maroni",
    order: 9,
    isCameo: false,
  },
  {
    movieRef: "The Dark Knight",
    personRef: "Christopher Nolan",
    role: "director",
    characterName: null,
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "The Dark Knight",
    personRef: "Emma Thomas",
    role: "producer",
    characterName: null,
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "The Dark Knight",
    personRef: "Wally Pfister",
    role: "producer",
    characterName: null,
    order: 3,
    isCameo: false,
  },
  {
    movieRef: "The Dark Knight",
    personRef: "Hans Zimmer",
    role: "producer",
    characterName: null,
    order: 4,
    isCameo: false,
  },
  {
    movieRef: "The Dark Knight",
    personRef: "Lee Smith",
    role: "producer",
    characterName: null,
    order: 5,
    isCameo: false,
  },

  // ========== INCEPTION ==========
  {
    movieRef: "Inception",
    personRef: "Leonardo DiCaprio",
    role: "actor",
    characterName: "Dom Cobb",
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "Inception",
    personRef: "Marion Cotillard",
    role: "actress",
    characterName: "Mal Cobb",
    order: 2,
    isCameo: false,
  },
  {
    movieRef: "Inception",
    personRef: "Tom Hardy",
    role: "actor",
    characterName: "Eames",
    order: 3,
    isCameo: false,
  },
  {
    movieRef: "Inception",
    personRef: "Ellen Page",
    role: "actress",
    characterName: "Ariadne",
    order: 4,
    isCameo: false,
  },
  {
    movieRef: "Inception",
    personRef: "Joseph Gordon-Levitt",
    role: "actor",
    characterName: "Arthur",
    order: 5,
    isCameo: false,
  },
  {
    movieRef: "Inception",
    personRef: "Michael Caine",
    role: "actor",
    characterName: "Professor Stephen Miles",
    order: 6,
    isCameo: false,
  },
  {
    movieRef: "Inception",
    personRef: "Cillian Murphy",
    role: "actor",
    characterName: "Robert Fischer",
    order: 7,
    isCameo: false,
  },
  {
    movieRef: "Inception",
    personRef: "Ken Watanabe",
    role: "actor",
    characterName: "Saito",
    order: 8,
    isCameo: false,
  },
  {
    movieRef: "Inception",
    personRef: "Dileep Rao",
    role: "actor",
    characterName: "Yusuf",
    order: 9,
    isCameo: false,
  },
  {
    movieRef: "Inception",
    personRef: "Pete Postlethwaite",
    role: "actor",
    characterName: "Maurice Fischer",
    order: 10,
    isCameo: false,
  },
  {
    movieRef: "Inception",
    personRef: "Lukas Haas",
    role: "actor",
    characterName: "Nash",
    order: 11,
    isCameo: false,
  },
  {
    movieRef: "Inception",
    personRef: "Christopher Nolan",
    role: "director",
    characterName: null,
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "Inception",
    personRef: "Emma Thomas",
    role: "producer",
    characterName: null,
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "Inception",
    personRef: "Wally Pfister",
    role: "producer",
    characterName: null,
    order: 3,
    isCameo: false,
  },
  {
    movieRef: "Inception",
    personRef: "Hans Zimmer",
    role: "producer",
    characterName: null,
    order: 4,
    isCameo: false,
  },
  {
    movieRef: "Inception",
    personRef: "Lee Smith",
    role: "producer",
    characterName: null,
    order: 5,
    isCameo: false,
  },

  // ========== THE SHAWSHANK REDEMPTION ==========
  {
    movieRef: "The Shawshank Redemption",
    personRef: "Tim Robbins",
    role: "actor",
    characterName: "Andy Dufresne",
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "The Shawshank Redemption",
    personRef: "Morgan Freeman",
    role: "actor",
    characterName: "Ellis Boyd 'Red' Redding",
    order: 2,
    isCameo: false,
  },
  {
    movieRef: "The Shawshank Redemption",
    personRef: "Bob Gunton",
    role: "actor",
    characterName: "Warden Norton",
    order: 3,
    isCameo: false,
  },
  {
    movieRef: "The Shawshank Redemption",
    personRef: "William Sadler",
    role: "actor",
    characterName: "Heywood",
    order: 4,
    isCameo: false,
  },
  {
    movieRef: "The Shawshank Redemption",
    personRef: "Clancy Brown",
    role: "actor",
    characterName: "Captain Hadley",
    order: 5,
    isCameo: false,
  },
  {
    movieRef: "The Shawshank Redemption",
    personRef: "James Whitmore",
    role: "actor",
    characterName: "Brooks Hatlen",
    order: 6,
    isCameo: false,
  },
  {
    movieRef: "The Shawshank Redemption",
    personRef: "Gil Bellows",
    role: "actor",
    characterName: "Tommy Williams",
    order: 7,
    isCameo: false,
  },
  {
    movieRef: "The Shawshank Redemption",
    personRef: "Mark Rolston",
    role: "actor",
    characterName: "Bogs Diamond",
    order: 8,
    isCameo: false,
  },
  {
    movieRef: "The Shawshank Redemption",
    personRef: "Frank Darabont",
    role: "director",
    characterName: null,
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "The Shawshank Redemption",
    personRef: "Roger Deakins",
    role: "producer",
    characterName: null,
    order: 1,
    isCameo: false,
  },

  // ========== SPIDER-MAN: ACROSS THE SPIDER-VERSE ==========
  {
    movieRef: "Spider-Man: Across the Spider-Verse",
    personRef: "Shameik Moore",
    role: "actor",
    characterName: "Miles Morales / Spider-Man (voice)",
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "Spider-Man: Across the Spider-Verse",
    personRef: "Hailee Steinfeld",
    role: "actress",
    characterName: "Gwen Stacy / Spider-Woman (voice)",
    order: 2,
    isCameo: false,
  },
  {
    movieRef: "Spider-Man: Across the Spider-Verse",
    personRef: "Oscar Isaac",
    role: "actor",
    characterName: "Miguel O'Hara / Spider-Man 2099 (voice)",
    order: 3,
    isCameo: false,
  },
  {
    movieRef: "Spider-Man: Across the Spider-Verse",
    personRef: "Jake Johnson",
    role: "actor",
    characterName: "Peter B. Parker / Spider-Man (voice)",
    order: 4,
    isCameo: false,
  },
  {
    movieRef: "Spider-Man: Across the Spider-Verse",
    personRef: "Joaquim Dos Santos",
    role: "director",
    characterName: null,
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "Spider-Man: Across the Spider-Verse",
    personRef: "Kemp Powers",
    role: "director",
    characterName: null,
    order: 2,
    isCameo: false,
  },
  {
    movieRef: "Spider-Man: Across the Spider-Verse",
    personRef: "Justin K. Thompson",
    role: "director",
    characterName: null,
    order: 3,
    isCameo: false,
  },
  {
    movieRef: "Spider-Man: Across the Spider-Verse",
    personRef: "Avi Arad",
    role: "producer",
    characterName: null,
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "Spider-Man: Across the Spider-Verse",
    personRef: "Phil Lord",
    role: "producer",
    characterName: null,
    order: 2,
    isCameo: false,
  },
  {
    movieRef: "Spider-Man: Across the Spider-Verse",
    personRef: "Christopher Miller",
    role: "producer",
    characterName: null,
    order: 3,
    isCameo: false,
  },
  {
    movieRef: "Spider-Man: Across the Spider-Verse",
    personRef: "Daniel Kaluuya",
    role: "actor",
    characterName: "Hobie Brown / Spider-Punk (voice)",
    order: 5,
    isCameo: false,
  },
  {
    movieRef: "Spider-Man: Across the Spider-Verse",
    personRef: "Issa Rae",
    role: "actress",
    characterName: "Jessica Drew / Spider-Woman (voice)",
    order: 6,
    isCameo: false,
  },
  {
    movieRef: "Spider-Man: Across the Spider-Verse",
    personRef: "Jason Schwartzman",
    role: "actor",
    characterName: "The Spot (voice)",
    order: 7,
    isCameo: false,
  },
  {
    movieRef: "Spider-Man: Across the Spider-Verse",
    personRef: "Brian Tyree Henry",
    role: "actor",
    characterName: "Jefferson Davis (voice)",
    order: 8,
    isCameo: false,
  },
  {
    movieRef: "Spider-Man: Across the Spider-Verse",
    personRef: "Luna Lauren Velez",
    role: "actress",
    characterName: "Rio Morales (voice)",
    order: 9,
    isCameo: false,
  },
  {
    movieRef: "Spider-Man: Across the Spider-Verse",
    personRef: "Greta Lee",
    role: "actress",
    characterName: "Lyla (voice)",
    order: 10,
    isCameo: false,
  },
  {
    movieRef: "Spider-Man: Across the Spider-Verse",
    personRef: "Amandla Stenberg",
    role: "actress",
    characterName: "Margo Kess / Spider-Byte (voice)",
    order: 11,
    isCameo: false,
  },
  {
    movieRef: "Spider-Man: Across the Spider-Verse",
    personRef: "Karan Soni",
    role: "actor",
    characterName: "Pavitr Prabhakar / Spider-Man India (voice)",
    order: 12,
    isCameo: false,
  },

  // ========== PATHAAN ==========
  {
    movieRef: "Pathaan",
    personRef: "Shah Rukh Khan",
    role: "actor",
    characterName: "Pathaan",
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "Pathaan",
    personRef: "Deepika Padukone",
    role: "actress",
    characterName: "Rubina Mohsin",
    order: 2,
    isCameo: false,
  },
  {
    movieRef: "Pathaan",
    personRef: "John Abraham",
    role: "actor",
    characterName: "Jim",
    order: 3,
    isCameo: false,
  },
  {
    movieRef: "Pathaan",
    personRef: "Siddharth Anand",
    role: "director",
    characterName: null,
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "Pathaan",
    personRef: "Aditya Chopra",
    role: "producer",
    characterName: null,
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "Pathaan",
    personRef: "Dimple Kapadia",
    role: "actress",
    characterName: "Nandini",
    order: 4,
    isCameo: false,
  },
  {
    movieRef: "Pathaan",
    personRef: "Ashutosh Rana",
    role: "actor",
    characterName: "Colonel Luthra",
    order: 5,
    isCameo: false,
  },
  {
    movieRef: "Pathaan",
    personRef: "Salman Khan",
    role: "actor",
    characterName: "Tiger (special appearance)",
    order: 6,
    isCameo: true,
  },
  {
    movieRef: "Pathaan",
    personRef: "Shaji Nadesan",
    role: "producer",
    characterName: null,
    order: 2,
    isCameo: false,
  },
  {
    movieRef: "Pathaan",
    personRef: "Sanchit Balhara",
    role: "producer",
    characterName: null,
    order: 3,
    isCameo: false,
  },

  // ========== JAWAN ==========
  {
    movieRef: "Jawan",
    personRef: "Shah Rukh Khan",
    role: "actor",
    characterName: "Azad Rathore / Vikram Rathore",
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "Jawan",
    personRef: "Nayanthara",
    role: "actress",
    characterName: "Narmada Rai",
    order: 2,
    isCameo: false,
  },
  {
    movieRef: "Jawan",
    personRef: "Vijay Sethupathi",
    role: "actor",
    characterName: "Kaalie Gaikwad",
    order: 3,
    isCameo: false,
  },
  {
    movieRef: "Jawan",
    personRef: "Priyamani",
    role: "actress",
    characterName: "Aishwarya Rathore",
    order: 4,
    isCameo: false,
  },
  {
    movieRef: "Jawan",
    personRef: "Deepika Padukone",
    role: "actress",
    characterName: "Aishwarya (special appearance)",
    order: 5,
    isCameo: true,
  },
  {
    movieRef: "Jawan",
    personRef: "Atlee",
    role: "director",
    characterName: null,
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "Jawan",
    personRef: "Sanya Malhotra",
    role: "actress",
    characterName: "Dr. Eeram",
    order: 6,
    isCameo: false,
  },
  {
    movieRef: "Jawan",
    personRef: "Ridhi Dogra",
    role: "actress",
    characterName: "Kaveri Amma",
    order: 7,
    isCameo: false,
  },
  {
    movieRef: "Jawan",
    personRef: "Anirudh Ravichander",
    role: "producer",
    characterName: null,
    order: 2,
    isCameo: false,
  },
  {
    movieRef: "Jawan",
    personRef: "Sunil Grover",
    role: "actor",
    characterName: "Kalki",
    order: 8,
    isCameo: false,
  },
  {
    movieRef: "Jawan",
    personRef: "Yogi Babu",
    role: "actor",
    characterName: "Jaffer",
    order: 9,
    isCameo: false,
  },
  {
    movieRef: "Jawan",
    personRef: "G. V. Prakash Kumar",
    role: "producer",
    characterName: null,
    order: 3,
    isCameo: false,
  },
  {
    movieRef: "Jawan",
    personRef: "Gauri Khan",
    role: "producer",
    characterName: null,
    order: 4,
    isCameo: false,
  },

  // ========== THE CONJURING ==========
  {
    movieRef: "The Conjuring",
    personRef: "Vera Farmiga",
    role: "actress",
    characterName: "Lorraine Warren",
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "The Conjuring",
    personRef: "Patrick Wilson",
    role: "actor",
    characterName: "Ed Warren",
    order: 2,
    isCameo: false,
  },
  {
    movieRef: "The Conjuring",
    personRef: "Lili Taylor",
    role: "actress",
    characterName: "Carolyn Perron",
    order: 3,
    isCameo: false,
  },
  {
    movieRef: "The Conjuring",
    personRef: "Ron Livingston",
    role: "actor",
    characterName: "Roger Perron",
    order: 4,
    isCameo: false,
  },
  {
    movieRef: "The Conjuring",
    personRef: "James Wan",
    role: "director",
    characterName: null,
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "The Conjuring",
    personRef: "Peter Safran",
    role: "producer",
    characterName: null,
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "The Conjuring",
    personRef: "Rob Cowan",
    role: "producer",
    characterName: null,
    order: 2,
    isCameo: false,
  },
  {
    movieRef: "The Conjuring",
    personRef: "Joey King",
    role: "actress",
    characterName: "Christine Perron",
    order: 5,
    isCameo: false,
  },
  {
    movieRef: "The Conjuring",
    personRef: "Mackenzie Foy",
    role: "actress",
    characterName: "Cindy Perron",
    order: 6,
    isCameo: false,
  },
  {
    movieRef: "The Conjuring",
    personRef: "John R. Leonetti",
    role: "producer",
    characterName: null,
    order: 3,
    isCameo: false,
  },
  {
    movieRef: "The Conjuring",
    personRef: "Shanley Caswell",
    role: "actress",
    characterName: "Andrea Perron",
    order: 7,
    isCameo: false,
  },
  {
    movieRef: "The Conjuring",
    personRef: "Hayley McFarland",
    role: "actress",
    characterName: "Nancy Perron",
    order: 8,
    isCameo: false,
  },
  {
    movieRef: "The Conjuring",
    personRef: "Sterling Jerins",
    role: "actress",
    characterName: "Judy Warren",
    order: 9,
    isCameo: false,
  },
  {
    movieRef: "The Conjuring",
    personRef: "Joseph Bishara",
    role: "producer",
    characterName: null,
    order: 4,
    isCameo: false,
  },

  // ========== LA LA LAND ==========
  {
    movieRef: "La La Land",
    personRef: "Ryan Gosling",
    role: "actor",
    characterName: "Sebastian Wilder",
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "La La Land",
    personRef: "Emma Stone",
    role: "actress",
    characterName: "Mia Dolan",
    order: 2,
    isCameo: false,
  },
  {
    movieRef: "La La Land",
    personRef: "John Legend",
    role: "actor",
    characterName: "Keith",
    order: 3,
    isCameo: false,
  },
  {
    movieRef: "La La Land",
    personRef: "J.K. Simmons",
    role: "actor",
    characterName: "Bill",
    order: 4,
    isCameo: false,
  },
  {
    movieRef: "La La Land",
    personRef: "Damien Chazelle",
    role: "director",
    characterName: null,
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "La La Land",
    personRef: "Linus Sandgren",
    role: "producer",
    characterName: null,
    order: 3,
    isCameo: false,
  },
  {
    movieRef: "La La Land",
    personRef: "Rosemarie DeWitt",
    role: "actress",
    characterName: "Laura",
    order: 5,
    isCameo: false,
  },
  {
    movieRef: "La La Land",
    personRef: "Finn Wittrock",
    role: "actor",
    characterName: "Greg",
    order: 6,
    isCameo: false,
  },
  {
    movieRef: "La La Land",
    personRef: "Callie Hernandez",
    role: "actress",
    characterName: "Tracy",
    order: 7,
    isCameo: false,
  },
  {
    movieRef: "La La Land",
    personRef: "Justin Hurwitz",
    role: "producer",
    characterName: null,
    order: 4,
    isCameo: false,
  },
  {
    movieRef: "La La Land",
    personRef: "Tom Everett Scott",
    role: "actor",
    characterName: "David",
    order: 8,
    isCameo: false,
  },
  {
    movieRef: "La La Land",
    personRef: "Jessica Rothe",
    role: "actress",
    characterName: "Alexis",
    order: 9,
    isCameo: false,
  },
  {
    movieRef: "La La Land",
    personRef: "Sonoya Mizuno",
    role: "actress",
    characterName: "Caitlin",
    order: 10,
    isCameo: false,
  },
  {
    movieRef: "La La Land",
    personRef: "Fred Berger",
    role: "producer",
    characterName: null,
    order: 5,
    isCameo: false,
  },
  {
    movieRef: "La La Land",
    personRef: "Jordan Horowitz",
    role: "producer",
    characterName: null,
    order: 6,
    isCameo: false,
  },

  // ========== GUARDIANS OF THE GALAXY VOL. 3 ==========
  {
    movieRef: "Guardians of the Galaxy Vol. 3",
    personRef: "Chris Pratt",
    role: "actor",
    characterName: "Peter Quill / Star-Lord",
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "Guardians of the Galaxy Vol. 3",
    personRef: "Zoe Saldana",
    role: "actress",
    characterName: "Gamora",
    order: 2,
    isCameo: false,
  },
  {
    movieRef: "Guardians of the Galaxy Vol. 3",
    personRef: "Dave Bautista",
    role: "actor",
    characterName: "Drax the Destroyer",
    order: 3,
    isCameo: false,
  },
  {
    movieRef: "Guardians of the Galaxy Vol. 3",
    personRef: "Karen Gillan",
    role: "actress",
    characterName: "Nebula",
    order: 4,
    isCameo: false,
  },
  {
    movieRef: "Guardians of the Galaxy Vol. 3",
    personRef: "Pom Klementieff",
    role: "actress",
    characterName: "Mantis",
    order: 5,
    isCameo: false,
  },
  {
    movieRef: "Guardians of the Galaxy Vol. 3",
    personRef: "Bradley Cooper",
    role: "actor",
    characterName: "Rocket (voice)",
    order: 6,
    isCameo: false,
  },
  {
    movieRef: "Guardians of the Galaxy Vol. 3",
    personRef: "Vin Diesel",
    role: "actor",
    characterName: "Groot (voice)",
    order: 7,
    isCameo: false,
  },
  {
    movieRef: "Guardians of the Galaxy Vol. 3",
    personRef: "Will Poulter",
    role: "actor",
    characterName: "Adam Warlock",
    order: 8,
    isCameo: false,
  },
  {
    movieRef: "Guardians of the Galaxy Vol. 3",
    personRef: "James Gunn",
    role: "director",
    characterName: null,
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "Guardians of the Galaxy Vol. 3",
    personRef: "Kevin Feige",
    role: "producer",
    characterName: null,
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "Guardians of the Galaxy Vol. 3",
    personRef: "Sean Gunn",
    role: "actor",
    characterName: "Kraglin Obfonteri / Rocket (on-set)",
    order: 9,
    isCameo: false,
  },
  {
    movieRef: "Guardians of the Galaxy Vol. 3",
    personRef: "Chukwudi Iwuji",
    role: "actor",
    characterName: "The High Evolutionary",
    order: 10,
    isCameo: false,
  },
  {
    movieRef: "Guardians of the Galaxy Vol. 3",
    personRef: "Elizabeth Debicki",
    role: "actress",
    characterName: "Ayesha",
    order: 11,
    isCameo: false,
  },
  {
    movieRef: "Guardians of the Galaxy Vol. 3",
    personRef: "Maria Bakalova",
    role: "actress",
    characterName: "Cosmo (voice)",
    order: 12,
    isCameo: false,
  },
  {
    movieRef: "Guardians of the Galaxy Vol. 3",
    personRef: "Sylvester Stallone",
    role: "actor",
    characterName: "Stakar Ogord",
    order: 13,
    isCameo: true,
  },
  {
    movieRef: "Guardians of the Galaxy Vol. 3",
    personRef: "John Murphy",
    role: "producer",
    characterName: null,
    order: 2,
    isCameo: false,
  },

  // ========== 3 IDIOTS ==========
  {
    movieRef: "3 Idiots",
    personRef: "Aamir Khan",
    role: "actor",
    characterName: "Ranchoddas Shamaldas Chanchad / Phunsukh Wangdu",
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "3 Idiots",
    personRef: "R. Madhavan",
    role: "actor",
    characterName: "Farhan Qureshi",
    order: 2,
    isCameo: false,
  },
  {
    movieRef: "3 Idiots",
    personRef: "Sharman Joshi",
    role: "actor",
    characterName: "Raju Rastogi",
    order: 3,
    isCameo: false,
  },
  {
    movieRef: "3 Idiots",
    personRef: "Kareena Kapoor Khan",
    role: "actress",
    characterName: "Pia Sahastrabuddhe",
    order: 4,
    isCameo: false,
  },
  {
    movieRef: "3 Idiots",
    personRef: "Boman Irani",
    role: "actor",
    characterName: "Viru Sahastrabuddhe (Virus)",
    order: 5,
    isCameo: false,
  },
  {
    movieRef: "3 Idiots",
    personRef: "Rajkumar Hirani",
    role: "director",
    characterName: null,
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "3 Idiots",
    personRef: "Vidhu Vinod Chopra",
    role: "producer",
    characterName: null,
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "3 Idiots",
    personRef: "Omi Vaidya",
    role: "actor",
    characterName: "Chatur Ramalingam (Silencer)",
    order: 6,
    isCameo: false,
  },
  {
    movieRef: "3 Idiots",
    personRef: "Mona Singh",
    role: "actress",
    characterName: "Mona Sahastrabuddhe",
    order: 7,
    isCameo: false,
  },
  {
    movieRef: "3 Idiots",
    personRef: "Javed Jaffrey",
    role: "actor",
    characterName: "Ranchoddas Narrator (older)",
    order: 8,
    isCameo: false,
  },
  {
    movieRef: "3 Idiots",
    personRef: "Shantanu Moitra",
    role: "producer",
    characterName: null,
    order: 2,
    isCameo: false,
  },
  {
    movieRef: "3 Idiots",
    personRef: "Parikshit Sahni",
    role: "actor",
    characterName: "Farhan's Father",
    order: 9,
    isCameo: false,
  },
  {
    movieRef: "3 Idiots",
    personRef: "Arun Bali",
    role: "actor",
    characterName: "Raju's Father",
    order: 10,
    isCameo: false,
  },
  {
    movieRef: "3 Idiots",
    personRef: "C. K. Muraleedharan",
    role: "producer",
    characterName: null,
    order: 3,
    isCameo: false,
  },

  // ========== AVATAR: THE WAY OF WATER ==========
  {
    movieRef: "Avatar: The Way of Water",
    personRef: "Sam Worthington",
    role: "actor",
    characterName: "Jake Sully",
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "Avatar: The Way of Water",
    personRef: "Zoe Saldana",
    role: "actress",
    characterName: "Neytiri",
    order: 2,
    isCameo: false,
  },
  {
    movieRef: "Avatar: The Way of Water",
    personRef: "Kate Winslet",
    role: "actress",
    characterName: "Ronal",
    order: 3,
    isCameo: false,
  },
  {
    movieRef: "Avatar: The Way of Water",
    personRef: "Sigourney Weaver",
    role: "actress",
    characterName: "Kiri",
    order: 4,
    isCameo: false,
  },
  {
    movieRef: "Avatar: The Way of Water",
    personRef: "Stephen Lang",
    role: "actor",
    characterName: "Colonel Miles Quaritch",
    order: 5,
    isCameo: false,
  },
  {
    movieRef: "Avatar: The Way of Water",
    personRef: "James Cameron",
    role: "director",
    characterName: null,
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "Avatar: The Way of Water",
    personRef: "Jon Landau",
    role: "producer",
    characterName: null,
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "Avatar: The Way of Water",
    personRef: "Cliff Curtis",
    role: "actor",
    characterName: "Tonowari",
    order: 6,
    isCameo: false,
  },
  {
    movieRef: "Avatar: The Way of Water",
    personRef: "Britain Dalton",
    role: "actor",
    characterName: "Lo'ak",
    order: 7,
    isCameo: false,
  },
  {
    movieRef: "Avatar: The Way of Water",
    personRef: "Trinity Bliss",
    role: "actress",
    characterName: "Tuktirey",
    order: 8,
    isCameo: false,
  },
  {
    movieRef: "Avatar: The Way of Water",
    personRef: "Russell Carpenter",
    role: "producer",
    characterName: null,
    order: 3,
    isCameo: false,
  },
  {
    movieRef: "Avatar: The Way of Water",
    personRef: "Jamie Flatters",
    role: "actor",
    characterName: "Neteyam",
    order: 9,
    isCameo: false,
  },
  {
    movieRef: "Avatar: The Way of Water",
    personRef: "Bailey Bass",
    role: "actress",
    characterName: "Tsireya",
    order: 10,
    isCameo: false,
  },
  {
    movieRef: "Avatar: The Way of Water",
    personRef: "Simon Franglen",
    role: "producer",
    characterName: null,
    order: 4,
    isCameo: false,
  },

  // ========== PARASITE ==========
  {
    movieRef: "Parasite",
    personRef: "Song Kang-ho",
    role: "actor",
    characterName: "Kim Ki-taek",
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "Parasite",
    personRef: "Lee Sun-kyun",
    role: "actor",
    characterName: "Park Dong-ik",
    order: 2,
    isCameo: false,
  },
  {
    movieRef: "Parasite",
    personRef: "Cho Yeo-jeong",
    role: "actress",
    characterName: "Choi Yeon-gyo",
    order: 3,
    isCameo: false,
  },
  {
    movieRef: "Parasite",
    personRef: "Choi Woo-shik",
    role: "actor",
    characterName: "Kim Ki-woo",
    order: 4,
    isCameo: false,
  },
  {
    movieRef: "Parasite",
    personRef: "Park So-dam",
    role: "actress",
    characterName: "Kim Ki-jung",
    order: 5,
    isCameo: false,
  },
  {
    movieRef: "Parasite",
    personRef: "Bong Joon-ho",
    role: "director",
    characterName: null,
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "Parasite",
    personRef: "Jang Hye-jin",
    role: "actress",
    characterName: "Kim Chung-sook",
    order: 6,
    isCameo: false,
  },
  {
    movieRef: "Parasite",
    personRef: "Park Myung-hoon",
    role: "actor",
    characterName: "Geun-se",
    order: 7,
    isCameo: false,
  },
  {
    movieRef: "Parasite",
    personRef: "Lee Jung-eun",
    role: "actress",
    characterName: "Gook Moon-gwang",
    order: 8,
    isCameo: false,
  },
  {
    movieRef: "Parasite",
    personRef: "Hong Kyung-pyo",
    role: "producer",
    characterName: null,
    order: 3,
    isCameo: false,
  },
  {
    movieRef: "Parasite",
    personRef: "Jung Ji-so",
    role: "actress",
    characterName: "Park Da-hye",
    order: 9,
    isCameo: false,
  },
  {
    movieRef: "Parasite",
    personRef: "Jung Hyeon-jun",
    role: "actor",
    characterName: "Park Da-song",
    order: 10,
    isCameo: false,
  },
  {
    movieRef: "Parasite",
    personRef: "Jung Jaeil",
    role: "producer",
    characterName: null,
    order: 4,
    isCameo: false,
  },
  {
    movieRef: "Parasite",
    personRef: "Kwak Sin-ae",
    role: "producer",
    characterName: null,
    order: 5,
    isCameo: false,
  },

  // ========== TOY STORY 4 ==========
  {
    movieRef: "Toy Story 4",
    personRef: "Tom Hanks",
    role: "actor",
    characterName: "Woody (voice)",
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "Toy Story 4",
    personRef: "Tim Allen",
    role: "actor",
    characterName: "Buzz Lightyear (voice)",
    order: 2,
    isCameo: false,
  },
  {
    movieRef: "Toy Story 4",
    personRef: "Annie Potts",
    role: "actress",
    characterName: "Bo Peep (voice)",
    order: 3,
    isCameo: false,
  },
  {
    movieRef: "Toy Story 4",
    personRef: "Tony Hale",
    role: "actor",
    characterName: "Forky (voice)",
    order: 4,
    isCameo: false,
  },
  {
    movieRef: "Toy Story 4",
    personRef: "Keanu Reeves",
    role: "actor",
    characterName: "Duke Caboom (voice)",
    order: 5,
    isCameo: false,
  },
  {
    movieRef: "Toy Story 4",
    personRef: "Christina Hendricks",
    role: "actress",
    characterName: "Gabby Gabby (voice)",
    order: 6,
    isCameo: false,
  },
  {
    movieRef: "Toy Story 4",
    personRef: "Josh Cooley",
    role: "director",
    characterName: null,
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "Toy Story 4",
    personRef: "Jordan Peele",
    role: "actor",
    characterName: "Bunny (voice)",
    order: 7,
    isCameo: false,
  },
  {
    movieRef: "Toy Story 4",
    personRef: "Keegan-Michael Key",
    role: "actor",
    characterName: "Ducky (voice)",
    order: 8,
    isCameo: false,
  },
  {
    movieRef: "Toy Story 4",
    personRef: "Ally Maki",
    role: "actress",
    characterName: "Giggle McDimples (voice)",
    order: 9,
    isCameo: false,
  },
  {
    movieRef: "Toy Story 4",
    personRef: "Joan Cusack",
    role: "actress",
    characterName: "Jessie (voice)",
    order: 10,
    isCameo: false,
  },
  {
    movieRef: "Toy Story 4",
    personRef: "Randy Newman",
    role: "producer",
    characterName: null,
    order: 2,
    isCameo: false,
  },
  {
    movieRef: "Toy Story 4",
    personRef: "Wallace Shawn",
    role: "actor",
    characterName: "Rex (voice)",
    order: 11,
    isCameo: false,
  },
  {
    movieRef: "Toy Story 4",
    personRef: "Bonnie Hunt",
    role: "actress",
    characterName: "Dolly (voice)",
    order: 12,
    isCameo: false,
  },
  {
    movieRef: "Toy Story 4",
    personRef: "Jeff Pidgeon",
    role: "actor",
    characterName: "Alien #1 (voice)",
    order: 13,
    isCameo: false,
  },
  {
    movieRef: "Toy Story 4",
    personRef: "Jonas Rivera",
    role: "producer",
    characterName: null,
    order: 3,
    isCameo: false,
  },
  {
    movieRef: "Toy Story 4",
    personRef: "Mark Nielsen",
    role: "producer",
    characterName: null,
    order: 4,
    isCameo: false,
  },

  // ========== JOHN WICK: CHAPTER 4 ==========
  {
    movieRef: "John Wick: Chapter 4",
    personRef: "Keanu Reeves",
    role: "actor",
    characterName: "John Wick",
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "John Wick: Chapter 4",
    personRef: "Donnie Yen",
    role: "actor",
    characterName: "Caine",
    order: 2,
    isCameo: false,
  },
  {
    movieRef: "John Wick: Chapter 4",
    personRef: "Bill Skarsgård",
    role: "actor",
    characterName: "Marquis de Gramont",
    order: 3,
    isCameo: false,
  },
  {
    movieRef: "John Wick: Chapter 4",
    personRef: "Laurence Fishburne",
    role: "actor",
    characterName: "Bowery King",
    order: 4,
    isCameo: false,
  },
  {
    movieRef: "John Wick: Chapter 4",
    personRef: "Ian McShane",
    role: "actor",
    characterName: "Winston",
    order: 5,
    isCameo: false,
  },
  {
    movieRef: "John Wick: Chapter 4",
    personRef: "Lance Reddick",
    role: "actor",
    characterName: "Charon",
    order: 6,
    isCameo: false,
  },
  {
    movieRef: "John Wick: Chapter 4",
    personRef: "Chad Stahelski",
    role: "director",
    characterName: null,
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "John Wick: Chapter 4",
    personRef: "Basil Iwanyk",
    role: "producer",
    characterName: null,
    order: 1,
    isCameo: false,
  },

  // ========== THE LION KING ==========
  {
    movieRef: "The Lion King",
    personRef: "Donald Glover",
    role: "actor",
    characterName: "Simba (voice)",
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "The Lion King",
    personRef: "Beyoncé",
    role: "actress",
    characterName: "Nala (voice)",
    order: 2,
    isCameo: false,
  },
  {
    movieRef: "The Lion King",
    personRef: "Seth Rogen",
    role: "actor",
    characterName: "Pumbaa (voice)",
    order: 3,
    isCameo: false,
  },
  {
    movieRef: "The Lion King",
    personRef: "Billy Eichner",
    role: "actor",
    characterName: "Timon (voice)",
    order: 4,
    isCameo: false,
  },
  {
    movieRef: "The Lion King",
    personRef: "Jon Favreau",
    role: "director",
    characterName: null,
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "The Lion King",
    personRef: "Keegan-Michael Key",
    role: "actor",
    characterName: "Kamari (voice)",
    order: 5,
    isCameo: false,
  },

  // ========== INTERSTELLAR ==========
  {
    movieRef: "Interstellar",
    personRef: "Matthew McConaughey",
    role: "actor",
    characterName: "Joseph Cooper",
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "Interstellar",
    personRef: "Anne Hathaway",
    role: "actress",
    characterName: "Dr. Amelia Brand",
    order: 2,
    isCameo: false,
  },
  {
    movieRef: "Interstellar",
    personRef: "Jessica Chastain",
    role: "actress",
    characterName: "Murphy Cooper (adult)",
    order: 3,
    isCameo: false,
  },
  {
    movieRef: "Interstellar",
    personRef: "Mackenzie Foy",
    role: "actress",
    characterName: "Murphy Cooper (child)",
    order: 4,
    isCameo: false,
  },
  {
    movieRef: "Interstellar",
    personRef: "Matt Damon",
    role: "actor",
    characterName: "Dr. Mann",
    order: 5,
    isCameo: false,
  },
  {
    movieRef: "Interstellar",
    personRef: "Michael Caine",
    role: "actor",
    characterName: "Professor Brand",
    order: 6,
    isCameo: false,
  },
  {
    movieRef: "Interstellar",
    personRef: "Christopher Nolan",
    role: "director",
    characterName: null,
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "Interstellar",
    personRef: "Emma Thomas",
    role: "producer",
    characterName: null,
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "Interstellar",
    personRef: "Hans Zimmer",
    role: "producer",
    characterName: null,
    order: 3,
    isCameo: false,
  },

  // ========== DANGAL ==========
  {
    movieRef: "Dangal",
    personRef: "Aamir Khan",
    role: "actor",
    characterName: "Mahavir Singh Phogat",
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "Dangal",
    personRef: "Fatima Sana Shaikh",
    role: "actress",
    characterName: "Geeta Phogat (adult)",
    order: 2,
    isCameo: false,
  },
  {
    movieRef: "Dangal",
    personRef: "Sanya Malhotra",
    role: "actress",
    characterName: "Babita Kumari (adult)",
    order: 3,
    isCameo: false,
  },
  {
    movieRef: "Dangal",
    personRef: "Sakshi Tanwar",
    role: "actress",
    characterName: "Daya Kaur",
    order: 4,
    isCameo: false,
  },
  {
    movieRef: "Dangal",
    personRef: "Aparshakti Khurana",
    role: "actor",
    characterName: "Omkar",
    order: 5,
    isCameo: false,
  },
  {
    movieRef: "Dangal",
    personRef: "Nitesh Tiwari",
    role: "director",
    characterName: null,
    order: 1,
    isCameo: false,
  },

  // ========== DUNE ==========
  {
    movieRef: "Dune",
    personRef: "Timothée Chalamet",
    role: "actor",
    characterName: "Paul Atreides",
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "Dune",
    personRef: "Zendaya",
    role: "actress",
    characterName: "Chani",
    order: 2,
    isCameo: false,
  },
  {
    movieRef: "Dune",
    personRef: "Rebecca Ferguson",
    role: "actress",
    characterName: "Lady Jessica",
    order: 3,
    isCameo: false,
  },
  {
    movieRef: "Dune",
    personRef: "Oscar Isaac",
    role: "actor",
    characterName: "Duke Leto Atreides",
    order: 4,
    isCameo: false,
  },
  {
    movieRef: "Dune",
    personRef: "Josh Brolin",
    role: "actor",
    characterName: "Gurney Halleck",
    order: 5,
    isCameo: false,
  },
  {
    movieRef: "Dune",
    personRef: "Javier Bardem",
    role: "actor",
    characterName: "Stilgar",
    order: 6,
    isCameo: false,
  },
  {
    movieRef: "Dune",
    personRef: "Dave Bautista",
    role: "actor",
    characterName: "Glossu Rabban",
    order: 7,
    isCameo: false,
  },
  {
    movieRef: "Dune",
    personRef: "Denis Villeneuve",
    role: "director",
    characterName: null,
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "Dune",
    personRef: "Greig Fraser",
    role: "producer",
    characterName: null,
    order: 1,
    isCameo: false,
  },
  {
    movieRef: "Dune",
    personRef: "Hans Zimmer",
    role: "producer",
    characterName: null,
    order: 3,
    isCameo: false,
  },

  // ========== Additional JOHN WICK: CHAPTER 4 Mappings ==========
  {
    movieRef: "John Wick: Chapter 4",
    personRef: "Shamier Anderson",
    role: "actor",
    characterName: "Tracker",
    order: 6,
    isCameo: false,
  },
  {
    movieRef: "John Wick: Chapter 4",
    personRef: "Rina Sawayama",
    role: "actress",
    characterName: "Akira",
    order: 7,
    isCameo: false,
  },
  {
    movieRef: "John Wick: Chapter 4",
    personRef: "Scott Adkins",
    role: "actor",
    characterName: "Killa",
    order: 8,
    isCameo: false,
  },
  {
    movieRef: "John Wick: Chapter 4",
    personRef: "Hiroyuki Sanada",
    role: "actor",
    characterName: "Shimazu",
    order: 9,
    isCameo: false,
  },
  {
    movieRef: "John Wick: Chapter 4",
    personRef: "Tyler Bates",
    role: "producer",
    characterName: null,
    order: 2,
    isCameo: false,
  },
  {
    movieRef: "John Wick: Chapter 4",
    personRef: "Joel J. Richard",
    role: "producer",
    characterName: null,
    order: 3,
    isCameo: false,
  },

  // ========== Additional THE LION KING Mappings ==========
  {
    movieRef: "The Lion King",
    personRef: "Chiwetel Ejiofor",
    role: "actor",
    characterName: "Scar (voice)",
    order: 6,
    isCameo: false,
  },
  {
    movieRef: "The Lion King",
    personRef: "Alfre Woodard",
    role: "actress",
    characterName: "Sarabi (voice)",
    order: 7,
    isCameo: false,
  },
  {
    movieRef: "The Lion King",
    personRef: "John Oliver",
    role: "actor",
    characterName: "Zazu (voice)",
    order: 8,
    isCameo: false,
  },
  {
    movieRef: "The Lion King",
    personRef: "James Earl Jones",
    role: "actor",
    characterName: "Mufasa (voice)",
    order: 9,
    isCameo: false,
  },
  {
    movieRef: "The Lion King",
    personRef: "Hans Zimmer",
    role: "producer",
    characterName: null,
    order: 2,
    isCameo: false,
  },
  {
    movieRef: "The Lion King",
    personRef: "Jeff Nathanson",
    role: "producer",
    characterName: null,
    order: 3,
    isCameo: false,
  },

  // ========== Additional INTERSTELLAR Mappings ==========
  {
    movieRef: "Interstellar",
    personRef: "John Lithgow",
    role: "actor",
    characterName: "Donald",
    order: 7,
    isCameo: false,
  },
  {
    movieRef: "Interstellar",
    personRef: "Casey Affleck",
    role: "actor",
    characterName: "Tom (older)",
    order: 8,
    isCameo: false,
  },
  {
    movieRef: "Interstellar",
    personRef: "Wes Bentley",
    role: "actor",
    characterName: "Doyle",
    order: 9,
    isCameo: false,
  },
  {
    movieRef: "Interstellar",
    personRef: "Topher Grace",
    role: "actor",
    characterName: "Getty",
    order: 10,
    isCameo: false,
  },
  {
    movieRef: "Interstellar",
    personRef: "Hoyte van Hoytema",
    role: "producer",
    characterName: null,
    order: 2,
    isCameo: false,
  },
  // Note: Hans Zimmer mapping already exists above for Interstellar

  // ========== Additional DANGAL Mappings ==========
  {
    movieRef: "Dangal",
    personRef: "Zaira Wasim",
    role: "actress",
    characterName: "Young Geeta Phogat",
    order: 5,
    isCameo: false,
  },
  {
    movieRef: "Dangal",
    personRef: "Girish Kulkarni",
    role: "actor",
    characterName: "Coach Pramod Kadam",
    order: 6,
    isCameo: false,
  },
  {
    movieRef: "Dangal",
    personRef: "Vivan Bhatena",
    role: "actor",
    characterName: "Coach at National Academy",
    order: 7,
    isCameo: false,
  },
  {
    movieRef: "Dangal",
    personRef: "Pritam",
    role: "producer",
    characterName: null,
    order: 2,
    isCameo: false,
  },
  {
    movieRef: "Dangal",
    personRef: "Satyajit Pande",
    role: "producer",
    characterName: null,
    order: 3,
    isCameo: false,
  },

  // ========== Additional DUNE Mappings ==========
  {
    movieRef: "Dune",
    personRef: "Stellan Skarsgård",
    role: "actor",
    characterName: "Baron Vladimir Harkonnen",
    order: 8,
    isCameo: false,
  },
  {
    movieRef: "Dune",
    personRef: "Charlotte Rampling",
    role: "actress",
    characterName: "Reverend Mother Gaius Helen Mohiam",
    order: 9,
    isCameo: false,
  },
  {
    movieRef: "Dune",
    personRef: "Jason Momoa",
    role: "actor",
    characterName: "Duncan Idaho",
    order: 10,
    isCameo: false,
  },
  {
    movieRef: "Dune",
    personRef: "Sharon Duncan-Brewster",
    role: "actress",
    characterName: "Dr. Liet Kynes",
    order: 11,
    isCameo: false,
  },
  {
    movieRef: "Dune",
    personRef: "Stephen McKeon",
    role: "producer",
    characterName: null,
    order: 3,
    isCameo: false,
  },
  {
    movieRef: "Dune",
    personRef: "Joe Walker",
    role: "producer",
    characterName: null,
    order: 4,
    isCameo: false,
  },
];

module.exports = movieRoleMappingSeedData;
