// Seed data for Movie model
// Real movies with diverse genres, categories, and adult ratings

const movieSeedData = [
  {
    title: "Oppenheimer",
    description: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.",
    language: "English",
    genre: ["Biography", "Drama", "Thriller"],
    categories: ["2D", "IMAX", "Dolby Cinema"],
    adultRating: "UA",
    imageURL: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800",
    durationInMinutes: 180,
    averageRating: 4.5,
    totalReviews: 1250,
    criticRating: 4.8,
  },
  {
    title: "Barbie",
    description: "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
    language: "English",
    genre: ["Comedy", "Adventure", "Fantasy"],
    categories: ["2D", "3D", "IMAX 3D"],
    adultRating: "U/A 7+",
    imageURL: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800",
    durationInMinutes: 114,
    averageRating: 4.2,
    totalReviews: 980,
    criticRating: 4.3,
  },
  {
    title: "The Dark Knight",
    description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    language: "English",
    genre: ["Action", "Crime", "Drama"],
    categories: ["2D", "IMAX"],
    adultRating: "UA",
    imageURL: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800",
    durationInMinutes: 152,
    averageRating: 4.9,
    totalReviews: 3500,
    criticRating: 4.9,
  },
  {
    title: "Inception",
    description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    language: "English",
    genre: ["Action", "Sci-Fi", "Thriller"],
    categories: ["2D", "IMAX", "Dolby Cinema"],
    adultRating: "UA",
    imageURL: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800",
    durationInMinutes: 148,
    averageRating: 4.8,
    totalReviews: 2900,
    criticRating: 4.7,
  },
  {
    title: "The Shawshank Redemption",
    description: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    language: "English",
    genre: ["Drama"],
    categories: ["2D", "Standard"],
    adultRating: "A",
    imageURL: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800",
    durationInMinutes: 142,
    averageRating: 4.9,
    totalReviews: 4200,
    criticRating: 5.0,
  },
  {
    title: "Spider-Man: Across the Spider-Verse",
    description: "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.",
    language: "English",
    genre: ["Animation", "Action", "Adventure"],
    categories: ["2D", "3D", "IMAX 3D", "4DX"],
    adultRating: "U/A 7+",
    imageURL: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800",
    durationInMinutes: 140,
    averageRating: 4.7,
    totalReviews: 1800,
    criticRating: 4.8,
  },
  {
    title: "Pathaan",
    description: "An Indian spy takes on the leader of a group of mercenaries who have nefarious plans to target his homeland.",
    language: "Hindi",
    genre: ["Action", "Thriller"],
    categories: ["2D", "3D", "IMAX 3D"],
    adultRating: "UA",
    imageURL: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800",
    durationInMinutes: 146,
    averageRating: 4.1,
    totalReviews: 2100,
    criticRating: 3.8,
  },
  {
    title: "Jawan",
    description: "A high-octane action thriller which outlines the emotional journey of a man who is set to rectify the wrongs in the society.",
    language: "Hindi",
    genre: ["Action", "Thriller", "Drama"],
    categories: ["2D", "3D", "IMAX"],
    adultRating: "UA",
    imageURL: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800",
    durationInMinutes: 169,
    averageRating: 4.3,
    totalReviews: 2500,
    criticRating: 4.0,
  },
  {
    title: "The Conjuring",
    description: "Paranormal investigators Ed and Lorraine Warren work to help a family terrorized by a dark presence in their farmhouse.",
    language: "English",
    genre: ["Horror", "Mystery", "Thriller"],
    categories: ["2D", "Standard"],
    adultRating: "A",
    imageURL: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800",
    durationInMinutes: 112,
    averageRating: 4.4,
    totalReviews: 1600,
    criticRating: 4.5,
  },
  {
    title: "La La Land",
    description: "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.",
    language: "English",
    genre: ["Musical", "Romance", "Drama"],
    categories: ["2D", "Dolby Cinema"],
    adultRating: "U/A 13+",
    imageURL: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800",
    durationInMinutes: 128,
    averageRating: 4.5,
    totalReviews: 1400,
    criticRating: 4.6,
  },
  {
    title: "Guardians of the Galaxy Vol. 3",
    description: "Still reeling from the loss of Gamora, Peter Quill rallies his team to defend the universe and one of their own - a mission that could mean the end of the Guardians if not successful.",
    language: "English",
    genre: ["Action", "Adventure", "Comedy"],
    categories: ["2D", "3D", "IMAX 3D", "4DX"],
    adultRating: "U/A 13+",
    imageURL: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800",
    durationInMinutes: 150,
    averageRating: 4.4,
    totalReviews: 1900,
    criticRating: 4.3,
  },
  {
    title: "3 Idiots",
    description: "Two friends are searching for their long lost companion. They revisit their college days and recall the memories of their friend who inspired them to think differently.",
    language: "Hindi",
    genre: ["Comedy", "Drama"],
    categories: ["2D", "Standard"],
    adultRating: "U/A 7+",
    imageURL: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800",
    durationInMinutes: 170,
    averageRating: 4.9,
    totalReviews: 3800,
    criticRating: 4.8,
  },
  {
    title: "Avatar: The Way of Water",
    description: "Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na'vi race to protect their home.",
    language: "English",
    genre: ["Action", "Adventure", "Fantasy"],
    categories: ["2D", "3D", "IMAX 3D", "4DX", "Dolby Cinema"],
    adultRating: "U/A 7+",
    imageURL: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800",
    durationInMinutes: 192,
    averageRating: 4.6,
    totalReviews: 2700,
    criticRating: 4.4,
  },
  {
    title: "Parasite",
    description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    language: "Korean",
    genre: ["Drama", "Thriller"],
    categories: ["2D", "Standard"],
    adultRating: "A",
    imageURL: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800",
    durationInMinutes: 132,
    averageRating: 4.7,
    totalReviews: 2200,
    criticRating: 4.9,
  },
  {
    title: "Toy Story 4",
    description: "When a new toy called 'Forky' joins Woody and the gang, a road trip alongside old and new friends reveals how big the world can be for a toy.",
    language: "English",
    genre: ["Animation", "Adventure", "Comedy"],
    categories: ["2D", "3D", "Dolby Cinema"],
    adultRating: "U",
    imageURL: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800",
    durationInMinutes: 100,
    averageRating: 4.6,
    totalReviews: 1700,
    criticRating: 4.7,
  },
  {
    title: "John Wick: Chapter 4",
    description: "John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe.",
    language: "English",
    genre: ["Action", "Thriller", "Crime"],
    categories: ["2D", "IMAX", "4DX", "Dolby Cinema"],
    adultRating: "A",
    imageURL: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800",
    durationInMinutes: 169,
    averageRating: 4.5,
    totalReviews: 1600,
    criticRating: 4.6,
  },
  {
    title: "The Lion King",
    description: "After the murder of his father, a young lion prince flees his kingdom only to learn the true meaning of responsibility and bravery.",
    language: "English",
    genre: ["Animation", "Adventure", "Drama"],
    categories: ["2D", "3D", "IMAX 3D"],
    adultRating: "U",
    imageURL: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800",
    durationInMinutes: 118,
    averageRating: 4.7,
    totalReviews: 3200,
    criticRating: 4.5,
  },
  {
    title: "Interstellar",
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    language: "English",
    genre: ["Adventure", "Drama", "Sci-Fi"],
    categories: ["2D", "IMAX", "Dolby Cinema"],
    adultRating: "U/A 13+",
    imageURL: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800",
    durationInMinutes: 169,
    averageRating: 4.8,
    totalReviews: 3100,
    criticRating: 4.7,
  },
  {
    title: "Dangal",
    description: "Former wrestler Mahavir Singh Phogat and his two wrestler daughters struggle towards glory at the Commonwealth Games in the face of societal oppression.",
    language: "Hindi",
    genre: ["Biography", "Drama", "Action"],
    categories: ["2D", "Standard"],
    adultRating: "U/A 7+",
    imageURL: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800",
    durationInMinutes: 161,
    averageRating: 4.8,
    totalReviews: 3400,
    criticRating: 4.7,
  },
  {
    title: "Dune",
    description: "Paul Atreides arrives on Arrakis after his father accepts the stewardship of the dangerous planet. However, chaos ensues after a betrayal as forces clash to control melange, a precious resource.",
    language: "English",
    genre: ["Adventure", "Sci-Fi", "Drama"],
    categories: ["2D", "3D", "IMAX", "IMAX 3D", "Dolby Cinema"],
    adultRating: "U/A 13+",
    imageURL: "https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=800",
    durationInMinutes: 155,
    averageRating: 4.5,
    totalReviews: 2000,
    criticRating: 4.6,
  },
];

module.exports = movieSeedData;
