// Seed data for Theatre model
// Real theatres across Bangalore, Mumbai, Nagpur, and Delhi

const theatreSeedData = [
  // Bangalore Theatres
  {
    name: "PVR INOX Forum Mall",
    plot: "21, Hosur Road",
    street: "Koramangala",
    city: "Bangalore",
    state: "Karnataka",
    country: "India",
    lat: "12.9344",
    lon: "77.6101",
    pinCode: 560029,
    averageRating: 4.3,
    totalReviews: 850,
  },
  {
    name: "Cinépolis Royal Meenakshi Mall",
    plot: "Bannerghatta Road",
    street: "Hulimavu",
    city: "Bangalore",
    state: "Karnataka",
    country: "India",
    lat: "12.8923",
    lon: "77.6045",
    pinCode: 560076,
    averageRating: 4.5,
    totalReviews: 720,
  },
  {
    name: "INOX Garuda Mall",
    plot: "Magrath Road",
    street: "Ashok Nagar",
    city: "Bangalore",
    state: "Karnataka",
    country: "India",
    lat: "12.9716",
    lon: "77.6031",
    pinCode: 560025,
    averageRating: 4.2,
    totalReviews: 950,
  },
  {
    name: "PVR Orion Mall",
    plot: "Dr. Rajkumar Road",
    street: "Rajajinagar",
    city: "Bangalore",
    state: "Karnataka",
    country: "India",
    lat: "12.9897",
    lon: "77.5422",
    pinCode: 560010,
    averageRating: 4.4,
    totalReviews: 1100,
  },
  {
    name: "Cinépolis Nexus Shantiniketan",
    plot: "Whitefield Main Road",
    street: "Whitefield",
    city: "Bangalore",
    state: "Karnataka",
    country: "India",
    lat: "12.9698",
    lon: "77.7500",
    pinCode: 560066,
    averageRating: 4.6,
    totalReviews: 680,
  },

  // Mumbai Theatres
  {
    name: "PVR Phoenix Palladium",
    plot: "High Street Phoenix",
    street: "Lower Parel",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    lat: "19.0024",
    lon: "72.8303",
    pinCode: 400013,
    averageRating: 4.7,
    totalReviews: 1450,
  },
  {
    name: "INOX R-City Mall",
    plot: "LBS Marg",
    street: "Ghatkopar West",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    lat: "19.0857",
    lon: "72.9089",
    pinCode: 400086,
    averageRating: 4.3,
    totalReviews: 920,
  },
  {
    name: "Cinépolis Seawoods Grand Central",
    plot: "Grand Central Mall",
    street: "Seawoods",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    lat: "19.0216",
    lon: "73.0169",
    pinCode: 400706,
    averageRating: 4.5,
    totalReviews: 780,
  },
  {
    name: "PVR INOX Juhu",
    plot: "Juhu Tara Road",
    street: "Juhu",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    lat: "19.1076",
    lon: "72.8263",
    pinCode: 400049,
    averageRating: 4.4,
    totalReviews: 1050,
  },
  {
    name: "Cinépolis Viviana Mall",
    plot: "Eastern Express Highway",
    street: "Thane West",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    lat: "19.2093",
    lon: "72.9720",
    pinCode: 400601,
    averageRating: 4.6,
    totalReviews: 840,
  },
  {
    name: "INOX Nariman Point",
    plot: "Eros Cinema Building",
    street: "Nariman Point",
    city: "Mumbai",
    state: "Maharashtra",
    country: "India",
    lat: "18.9262",
    lon: "72.8226",
    pinCode: 400021,
    averageRating: 4.2,
    totalReviews: 650,
  },

  // Nagpur Theatres
  {
    name: "PVR Emporia Mall",
    plot: "Central Bazar Road",
    street: "Ramdaspeth",
    city: "Nagpur",
    state: "Maharashtra",
    country: "India",
    lat: "21.1458",
    lon: "79.0882",
    pinCode: 440010,
    averageRating: 4.3,
    totalReviews: 520,
  },
  {
    name: "Cinépolis City One Mall",
    plot: "Kingsway Road",
    street: "Panchsheel Square",
    city: "Nagpur",
    state: "Maharashtra",
    country: "India",
    lat: "21.1291",
    lon: "79.0708",
    pinCode: 440001,
    averageRating: 4.4,
    totalReviews: 460,
  },
  {
    name: "INOX Jaswant Tuli Mall",
    plot: "Wardha Road",
    street: "Shankar Nagar",
    city: "Nagpur",
    state: "Maharashtra",
    country: "India",
    lat: "21.1307",
    lon: "79.0472",
    pinCode: 440025,
    averageRating: 4.2,
    totalReviews: 380,
  },
  {
    name: "Cinépolis VR Nagpur",
    plot: "Wardha Road",
    street: "Wardha Road",
    city: "Nagpur",
    state: "Maharashtra",
    country: "India",
    lat: "21.1050",
    lon: "79.0537",
    pinCode: 440015,
    averageRating: 4.5,
    totalReviews: 550,
  },

  // Delhi Theatres
  {
    name: "PVR Select Citywalk",
    plot: "Saket District Centre",
    street: "Saket",
    city: "Delhi",
    state: "Delhi",
    country: "India",
    lat: "28.5275",
    lon: "77.2169",
    pinCode: 110017,
    averageRating: 4.6,
    totalReviews: 1250,
  },
  {
    name: "PVR Priya Vasant Vihar",
    plot: "Priya Cinema Complex",
    street: "Vasant Vihar",
    city: "Delhi",
    state: "Delhi",
    country: "India",
    lat: "28.5620",
    lon: "77.1573",
    pinCode: 110057,
    averageRating: 4.3,
    totalReviews: 890,
  },
  {
    name: "INOX Nehru Place",
    plot: "Epicuria Mall",
    street: "Nehru Place",
    city: "Delhi",
    state: "Delhi",
    country: "India",
    lat: "28.5494",
    lon: "77.2503",
    pinCode: 110019,
    averageRating: 4.1,
    totalReviews: 720,
  },
  {
    name: "Cinépolis DLF Place",
    plot: "DLF Place Mall",
    street: "Saket",
    city: "Delhi",
    state: "Delhi",
    country: "India",
    lat: "28.5230",
    lon: "77.2115",
    pinCode: 110017,
    averageRating: 4.5,
    totalReviews: 980,
  },
  {
    name: "PVR Rivoli Connaught Place",
    plot: "Kasturba Gandhi Marg",
    street: "Connaught Place",
    city: "Delhi",
    state: "Delhi",
    country: "India",
    lat: "28.6304",
    lon: "77.2177",
    pinCode: 110001,
    averageRating: 4.4,
    totalReviews: 1150,
  },
  {
    name: "INOX Sapphire 83",
    plot: "Mall Road",
    street: "Malviya Nagar",
    city: "Delhi",
    state: "Delhi",
    country: "India",
    lat: "28.5355",
    lon: "77.2084",
    pinCode: 110017,
    averageRating: 4.2,
    totalReviews: 640,
  },
];

module.exports = theatreSeedData;
